### ISSUE TITLE
current running total for a configurable period.

### ISSUE THREAD

**Issue by janvda** [jaggr2/node-red-contrib-aggregator#10]
I would like to request a new feature for this node .

The idea is that it should output the current running total for a configurable period.

1. So each time a message for a certain topic arrives, it should calculate the running total of all the messages received for that topic in the period [ now - configurable period, now] and then immediately output this running total.

2. A further improvement: when no messages are received within a configurable period for a topic for which we have received a message earlier that it outputs 0 as running total for that topic.  (There is no need to send a 0 again when next time that configurable period has ended).

I would like to use this feature for my water meter; every 5 seconds I receive the number of pulses counted (in many cases only 0, 1 or 2 pulses are counted during this interval) - so it would be interesting to get a running total over an interval of 1 minute (or more) which would tell me the amount of water used in the last minute which I would then display in the node-red dashboard gauge.

3. another extension - is that besides "running total" we also support a "running average".  I think that this is a simple extension.

**Comment by janvda** [comment]
I just discovered [node-red-node-smooth](https://github.com/node-red/node-red-nodes/tree/master/function/smooth).

So this node can be used in case the messages are arriving at a fixed rate (e.g. once every 5 seconds).

So this node currently addresses my issue.

**Comment by jaggr2** [comment]
I'm closing this, please reopen if the feature is still requested
