### ISSUE TITLE
Node topic does not honor case

### ISSUE THREAD

**Issue by rrroonn** [jaggr2/node-red-contrib-aggregator#14]
If a msg.topic is received as input by the node, it is converted to a lowercase variant - which is a problem if the topic is an MQTT topic as MQTT is case sensitive.  This results in data being published in the wrong place.

The node should not alter the case of any input topic and I cannot think where it would make sense to change the case.  I suspect that it is part of the internal logic to test and aggregate "per topic", however, it would be better to have a "Topics are case-sensitive" option as part of the node.

thank you.

**Comment by kuema** [comment]
I stumbled upon the same problem. I also think it would be better to leave the topic case unchanged, as it is given by the input. 

With recent versions of Node-RED you can simple put a `change` node with a JSONata expression (`$lowercase(topic)`) in front, that does the conversion for you. No need to overload this node with more options than necessary. :smile:

**Comment by jaggr2** [comment]
I just made a new major version that does not anymore convert the topic to lowercase.
