### ISSUE TITLE
Aggregator doesn't honour local timezone

### ISSUE THREAD

**Issue by AcEIoXx** [jaggr2/node-red-contrib-aggregator#15]
I am at CET but all the time-out actions of node-red-contrib-aggregator are always on UTC

Please change it so that for example the daily aggregation is done on 0:00 instead of 1:00
For example if it is set to 4 hours it should run at 16:00 according to the documentation. But it runs at 17:00 for me.

PS. system timezone is cet to europe/amsterdam
Node-red settings.js also has this timezone set.

Node-Red has the correct time shown everywhere.
The server it is running on (freebsd 12.1-RELEASE ) also shows the correct time.

With my basic knowledge I should find something like Date().getTimezoneOffset() in the code to be able to counteract the offset so it would run at the correct time. Though I can't find anything like that. This because new Date().getTime(); should always return the EPOCH time, which is always based on UTC as far as I understood.

**Comment by AcEIoXx** [comment]
For now I changed the code so that it will work for me (correct the startup time for all timezones to calculate 00:00 for the machine time zone).
If you are interested in my changes let me know and I will gladly share them as they are literally just a few changes.

**Comment by AcEIoXx** [comment]
I created at a fork with a fix for the problem. See pull request #16 
It's quick and dirty, but it works.

**Comment by jaggr2** [comment]
Thx for your help, I just merged your PR!
