### ISSUE TITLE
Does not aggregate zeros

### ISSUE THREAD

**Issue by Paul-Reed** [jaggr2/node-red-contrib-aggregator#2]
Using the aggregator node to reduce the number of datapoints in my nodered dashboard that monitors solar generation.
Works well for both positive & negative numbers, but when solar generation is zero (at night), the aggregator does not produce an output.
It seems to struggle finding the mean value of 0 + 0 + 0 + 0 + 0, which I expected to be '0'.

**Comment by jaggr2** [comment]
I was surprised that I haven't recognised this error before. Anyhow I published version 1.1.1 to npm which fixes this issue. Please update the node to this version and let me know if you have any further issues :)

**Comment by Paul-Reed** [comment]
Great, thank you.
Works well now.

Paul
