### ISSUE TITLE
Error in setTimeout(function ()

### ISSUE THREAD

**Issue by alan-rpi** [jaggr2/node-red-contrib-aggregator#4]
Very useful node :) 

I'm using version "1.2.0". While trying to get my head around the "Submit incomplete interval on start?" option I discovered that in the setTimeout(function () that node.submitIncompleteInterval is undefined. Changing it to config.submitIncompleteInterval works:

node.primaryTimeout = setTimeout(function () {

	console.log("node.intervalTimeout "+node.intervalTimeout);
	console.log("node.startupTimeout "+node.startupTimeout);
	console.log("node.submitIncompleteInterval "+node.submitIncompleteInterval);
	
	node.interval = setInterval(node.aggregateAll, node.intervalTimeout);
			
	if (config.submitIncompleteInterval) node.aggregateAll();	// was if (node.sub.....
						
}, node.startupTimeout);

Welcome to Node-RED
===================

29 Jan 21:05:20 - [info] Node-RED version: v0.16.0
29 Jan 21:05:20 - [info] Node.js  version: v4.7.2
29 Jan 21:05:20 - [info] Linux 4.4.38+ arm LE
29 Jan 21:05:26 - [info] Loading palette nodes
29 Jan 21:06:05 - [info] Dashboard version 2.2.1 started at /ui
29 Jan 21:06:07 - [info] Settings file  : /home/pi/.node-red/settings.js
29 Jan 21:06:07 - [info] User directory : /home/pi/.node-red
29 Jan 21:06:07 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypison
29 Jan 21:06:07 - [info] Server now running at http://127.0.0.1:1880/
29 Jan 21:06:07 - [info] Starting flows
29 Jan 21:06:08 - [info] Started flows
node.intervalTimeout 120000
node.startupTimeout 112303
node.submitIncompleteInterval undefined

--------------------------
I've also written an explanation of this function and time of aggregations in general:

#### Submit incomplete interval on start? option
	The Aggregator node aggregates on a whole unit of time selected. For example, every 4 hours starting at 12:30:00 will aggregate at [16:00:00], 20:00:00, 00:00:00 etc. Time in [ ] depends on the "Submit incomplete interval on start?" setting.
	
	If "Submit incomplete interval on start?" is not ticked then will wait until a complete unit of time selected has passed. For example, every 2 mins starting at 12:00:20 then 12:04:00*, 12.06:00 etc. *So 3m 40s has passed before the first aggregation.
	
	If "Submit incomplete interval on start?" is ticked then will wait until the next whole unit of time selected arrives. For example, every 2 mins starting at 12:00:20 then 12:02:00*, 12:04.00, 12.06:00 etc. *So 1m 40s has passed before the first aggregation.

**Comment by jaggr2** [comment]
Thank you for your feedback :)

Yes, the node.submitIncompleteInterval should be config.submitIncompleteInterval. I'll fix that as soon as possible (hope in the next days)

Your explanation for the "submit incomplete interval on start" option is correct. I've took the freedom to rewrite it a little bit in hope to give some more informations. Please correct me if I made it worse.

> The Aggregator node aggregates on a whole unit of time selected. For example, every 4 hours starting at 12:30:00 will aggregate at [16:00:00], 20:00:00, 00:00:00 etc. The first aggregation result at 16:00:00, containing the values over the first "incomplete" timespan of 3.5 hours (12:30 - 16:00), is only outputted if the "Submit incomplete interval on start?" option is selected. If the option is not selected, the first output would be at 20:00 with the values between 16:00 and 20:00.
> 
> In practise this option should be deselected if you have to ensure that all aggregation results are based on an equal timespan. If this is not an issue or you explicitly want also the first values aggregated for your application, then this option should be selected.

**Comment by alan-rpi** [comment]
Your text is better as I did not notice that if the "Submit incomplete interval on start?" option is NOT selected then the initial values are ignored - I had incorrectly presumed that they were included in the next full time period.

For my own use I have made a significant change to Aggregator to optionally output by Topic. I was going to offer this to you as an update to Aggregator but I now think it is better as a separate node (AggregatorBT). I will leave you name (and the other author's name) in the README file. Hope this is OK. I think I will now put an option in to run the time periods from the node start time.  "Submit incomplete interval on start?" is then not applicable.

I am also writing a Gather-Split node that takes multiple inputs and creates outputs by topic that can then be fed into AggregatorBT. For example, with 5x DHT22 inputs the outputs are 10 messages: 5 with Topic=Temperature and 5 with Topic=Humidity. AggregatorBT will then give (say) the average temperature and average humidity over the time period (the overall average is meaningless). 

Alternatively, Gather-Split can set the topic to the device name and send the temperature and humidity outputs to channels 3 & 4 respectively. So for example, one AggregatorBT then gives the average temperature by room name and overall average temperature for the house, and another AggregatorBT does the same for humidity.

Gather-Split can optionally produce a summary record on channel 2 that has the latest readings from each input when all inputs, or 'n' inputs, have sent readings. This single summary message that be used in a subsequent node to analyse multiple outputs (e.g. if any room is < 5 degrees and the outside temperature is < 0 degrees then turn on the heating). AggregatorBT also has an optional summary of all aggregations by Topic. This is like a spreadsheet row with multiple columns that can then be graphed as multiple lines by time (a timestamp is also optionally output in both nodes).

**Comment by alan-rpi** [comment]
Roger,
I've just been testing my variation and your revised text
> If the option is not selected, the first output would be at 20:00 with the values between 16:00 and 20:00.
is wrong I believe as the node.values array is only cleared after aggregateAll completes (at the end on line 86). In the example the aggregation at 20:00 will have the values between 12:30 and 20:00.

Here is a test with a cycle time of 15 secs and Submit incomplete interval on start?  **not** ticked
Deployed at 18:23:02
07/02/2017, 18:23:07node: 73e5cf1.bba69bHall : msg.payload : string[1]  "5"
07/02/2017, 18:23:07node: 73e5cf1.bba69bHall : msg.payload : string[2] "10"
07/02/2017, 18:23:07node: 73e5cf1.bba69bHall : msg.payload : string[2] "15"
< no aggregation at 18:23:15>
07/02/2017, 18:23:22node: 9411f89.fea1808Hall : msg.payload : string[2] "50"
< aggregation at 18:23:30>
07/02/2017, 18:23:32node: c6782b21.e8c228msg.payload : number 20
As the average is 20 and not 50 then the earlier data **has** been included (5+10+15+50 =80/4=20)

If you agree then there is a choice: amend the text or amend the function. My decision would be to exclude them so that any analysis of message data over time period is consistent. That means changing line 127 in the timer from:
`	if (config.submitIncompleteInterval) node.aggregateAll();	`
to
`	if (config.submitIncompleteInterval) {
                node.aggregateAll();	// aggregates and clears data
      } else {
               node.values = {};             // throw away data 
     }`

Please tell me your decision so I can make my variation consistent.

Alan

**Comment by jaggr2** [comment]
Hi Alan,

Thank you very much for testing this case that much. I share your decision to exclude them and changing line 127 to throw away data. I'll publish a correction soon.

Roger

**Comment by jaggr2** [comment]
Alan,

I've published version 1.3.0 on npm which closes this issue. 

> For my own use I have made a significant change to Aggregator to optionally output by Topic.

I once had the same idea but I solved it with a node-red custom function node which was splitting the messages by topics to two independent aggregator nodes. Since this seems to be a popular use case this could be a feature for an aggregator version 2. 

> I was going to offer this to you as an update to Aggregator but I now think it is better as a separate node (AggregatorBT). I will leave you name (and the other author's name) in the README file. Hope this is OK. I think I will now put an option in to run the time periods from the node start time. "Submit incomplete interval on start?" is then not applicable.

Yes, feel free to use and manipulate the aggregator as much as you like :)

Your Gather-Split node sounds very interesting. I haven't had such scenarios until now but this makes sense to me.

Roger
