### ISSUE TITLE
problem with SUM

### ISSUE THREAD

**Issue by townet01** [jaggr2/node-red-contrib-aggregator#5]
Hello,
I try to SUM 3 multiple input with several topics. The "aggregator" node answer with correct value (the sum of task1+task2+task3) only if I set 1 second of "every". And in this case, several results are missing (1 on 6). Why ??

Thanks
E-

**Comment by jaggr2** [comment]
Hello,

I'm currently abroad until next week. In the meantime: Can you provide me an example of messages with values/topic/time you've sent to the aggregator node and what result you are expecting? It's the first time I hear that values are missing, so I'm curious wether it's a bug or a lack of documentation/misunderstanding.

Thanks!

**Comment by townet01** [comment]
25/3/2017, 15:49:03node: 29c07c36.bb3414
task2 : msg.payload : number
2.365
25/3/2017, 15:49:03node: 29c07c36.bb3414
task1 : msg.payload : number
2.87166
25/3/2017, 15:49:03node: 29c07c36.bb3414
task3 : msg.payload : number
1.49766
25/3/2017, 15:49:03node: 29c07c36.bb3414
task5 : msg.payload : number
2.0777599999999996
25/3/2017, 15:49:03node: 29c07c36.bb3414
task4 : msg.payload : number
-0.17862
25/3/2017, 15:49:04node: 29c07c36.bb3414
task2 : msg.payload : number
2.2825
25/3/2017, 15:49:04node: 29c07c36.bb3414
task1 : msg.payload : number
3.1327200000000004
25/3/2017, 15:49:04node: 29c07c36.bb3414
task3 : msg.payload : number
1.49766
25/3/2017, 15:49:04node: 29c07c36.bb3414
task5 : msg.payload : number
1.6225
25/3/2017, 15:49:04node: 29c07c36.bb3414
task4 : msg.payload : number
-0.17862

**Comment by jaggr2** [comment]
I made a test setup where I manually injected your values. The timespan setting in the aggregator-node was set to every 10 seconds. I tried different time breaks between the injections of the values. In the following screenshot I tested the case when all 10 values are injected in the same 10s timespan and checked the result with Microsoft Excel:

![aggregator_sum_test](https://cloud.githubusercontent.com/assets/3640044/24667496/ff70a28c-1963-11e7-98f1-e86b2c2fe49d.jpg)

Sadly I could not detect any problem. 

Please note that after every timespan (the "every" setting):

1. the aggegrator-node calculates the sum
2. output this as message
3. **throws away the retrieved values**
4. and starts again recording values for the configured timespan

Are you expecting that the aggregator-node calculates a continuous sum with an intermediate result every xxx seconds? 
If yes: this is not possible with the current implementation, but would be an interesting feature.
If no: Please add some more details explaining the problem

**Comment by townet01** [comment]
Ok, i assumed that:
- Every "x" seconds, the node gives me back the SUM of payloads, ALSO if that all payloads aren't arrived yet.
But, is in this case, the SUM correct ??!
Or is the node waiting for several complete cycles (n*[task1+task2+task3+task4+task5] ?

And yes... the first assumption is a good idea and an interesting feature :-)

Thanks
E

**Comment by alan-rpi** [comment]
Hi E, I'm not 100% sure what you want but I am developing a variation of this node called aggregator-by-topic. It's still under test but basically will allow:

1. output an aggregation for each topic as well as the overall aggregation
2. aggregation by time (as now), by message count or by a message matching a string value
3. receives commands to start and stop the aggregations, reset the timer/count/match, force an aggregation or a sub-aggregation,

The sub-aggregation command will, for example, sum all the topics and output a summary  message with all the topic aggregations as well as the overall aggregation, but will not reset the topic summations to zero. So each sub-aggregation will give a cumulative sum until the timer/count/match is triggered. If time/count is set very large or the match never happens, then cumulative aggregation will go on for ever (but could be memory problems if too many values are stored).

The count option will trigger an aggregation when x number of messages has arrived. Maybe that is what you want? But note it is an overall count, so there may be topics that have not been received. 

If you have n topics and want an aggregation when at least one message has been received for each topic then aggregator-by-topic does not support that, but that maybe a useful addition.

At the moment I can not make any commitments to say when aggregator-by-topic will be released.

**Comment by jaggr2** [comment]
Hi

I'm cleaning up old issues. Please reopen if this is still an issue.
