### ISSUE TITLE
aggregation of multipe topics

### ISSUE THREAD

**Issue by ghost** [jaggr2/node-red-contrib-aggregator#6]
Hi,
  woudl it be possible to enrich the node with the following feature:
 A1) possible to gave more than one input where
     A1.1) to each a selectable aggregator function can be assigned
 B) all aggregations for each topic all collected into msg.payload
     { topic1: aggregation1, topic2:aggregation2,...}

all  aggregation interval shall apply for all topics

Many thanks!

**Comment by jaggr2** [comment]
Hi
A) It seems like node-red allows only one input per node. So we would have to implement some configurable splitting function. But that is probably better done in a separate node and then just add the aggegrator node to each output of this "splitting node" output in the node-red editor panel.
B) Yes, this would be possible. I am very busy the next weeks so this could take some time. PRs are welcome :)

**Comment by jaggr2** [comment]
I'm closing this, please reopen if feature is still requested
