### ISSUE TITLE
Error with Serial Node

### ISSUE THREAD

**Issue by ambrosekwok** [jaggr2/node-red-contrib-aggregator#8]
Hi,

I got below error when a serial node is connected in node-red flow.

msg : string[44]
"Cannot read property 'toString' of undefined"

Accelerometor send data via serial (hex string: <Buffer 80 07 7f f3 80 07 0a>), and next function node convert it to decimal number and calculate the acceleration value.
![selection_002](https://user-images.githubusercontent.com/37961681/38166052-c8d20a78-354f-11e8-9ae6-d2aedb40a7cc.png)

Below flows work normal, but error occurred when serial connected. 
![selection_003](https://user-images.githubusercontent.com/37961681/38166502-308c60e4-3557-11e8-8333-941dd2007229.png)

Can the aggregator node work with serial node? any parameter should modified on the nodes?

Thanks a lot.

ambrose

**Comment by jaggr2** [comment]
Hi, the aggregator node throws this error when the msg.topic is null or undefined ( same error as in issue #7 ). I'll make a fix for that.

**Comment by gormac** [comment]
@ambrosekwok This issues was solved with the release of version `1.4.0`.

@jaggr2 Please close this issue and consider tagging the master branch with a `1.4.0` tag.

**Comment by jaggr2** [comment]
@gormac Thx for fixing it!
